const products = [
  {
    id: 1,
    name: "Classic T-Shirt",
    description: "100% cotton, comfortable and breathable",
    price: 19.99,
    imageUrl: "https://example.com/images/tshirt.jpg",
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "Denim Jacket",
    description: "Stylish denim jacket for all seasons",
    price: 59.99,
    imageUrl: "https://example.com/images/denim-jacket.jpg",
    category: "Women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 3,
    name: "Blue Jeans",
    description: "Slim-fit jeans with stretch fabric",
    price: 39.99,
    imageUrl: "https://example.com/images/jeans.jpg",
    category: "Men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 4,
    name: "Summer Dress",
    description: "Lightweight dress perfect for summer",
    price: 49.99,
    imageUrl: "https://example.com/images/summer-dress.jpg",
    category: "Women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 5,
    name: "Kids Hoodie",
    description: "Soft hoodie with fun prints for kids",
    price: 29.99,
    imageUrl: "https://example.com/images/kids-hoodie.jpg",
    category: "Kids",
    sizes: ["S", "M", "L"],
  },
  {
    id: 6,
    name: "Leather Jacket",
    description: "Premium leather jacket with a modern fit",
    price: 129.99,
    imageUrl: "https://example.com/images/leather-jacket.jpg",
    category: "Men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 7,
    name: "Floral Skirt",
    description: "Elegant skirt with floral patterns",
    price: 34.99,
    imageUrl: "https://example.com/images/floral-skirt.jpg",
    category: "Women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 8,
    name: "Kids Jeans",
    description: "Durable and comfortable jeans for kids",
    price: 24.99,
    imageUrl: "https://example.com/images/kids-jeans.jpg",
    category: "Kids",
    sizes: ["S", "M", "L"],
  },
  {
    id: 9,
    name: "Hooded Sweatshirt",
    description: "Warm and cozy hoodie for casual wear",
    price: 44.99,
    imageUrl: "https://example.com/images/hoodie.jpg",
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 10,
    name: "Graphic Tee",
    description: "Trendy graphic t-shirt with cool prints",
    price: 22.99,
    imageUrl: "https://example.com/images/graphic-tee.jpg",
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 11,
    name: "Maxi Dress",
    description: "Flowy maxi dress for summer outings",
    price: 54.99,
    imageUrl: "https://example.com/images/maxi-dress.jpg",
    category: "Women",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 12,
    name: "Leather Boots",
    description: "Durable and stylish leather boots",
    price: 89.99,
    imageUrl: "https://example.com/images/leather-boots.jpg",
    category: "Men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 13,
    name: "Kids Sneakers",
    description: "Comfortable sneakers for everyday wear",
    price: 34.99,
    imageUrl: "https://example.com/images/kids-sneakers.jpg",
    category: "Kids",
    sizes: ["S", "M", "L"],
  },
  {
    id: 14,
    name: "Cardigan Sweater",
    description: "Lightweight cardigan for layering",
    price: 39.99,
    imageUrl: "https://example.com/images/cardigan.jpg",
    category: "Women",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 15,
    name: "Chinos Pants",
    description: "Casual chinos for office or weekend",
    price: 42.99,
    imageUrl: "https://example.com/images/chinos.jpg",
    category: "Men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 16,
    name: "Summer Shorts",
    description: "Comfortable cotton shorts for warm weather",
    price: 19.99,
    imageUrl: "https://example.com/images/summer-shorts.jpg",
    category: "Men",
    sizes: ["S", "M", "L"],
  },
  {
    id: 17,
    name: "Pleated Skirt",
    description: "Chic pleated skirt for women",
    price: 32.99,
    imageUrl: "https://example.com/images/pleated-skirt.jpg",
    category: "Women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 18,
    name: "Kids T-Shirt Set",
    description: "2-pack cotton t-shirts for kids",
    price: 21.99,
    imageUrl: "https://example.com/images/kids-tshirt-set.jpg",
    category: "Kids",
    sizes: ["S", "M", "L"],
  },
  {
    id: 19,
    name: "Windbreaker Jacket",
    description: "Lightweight jacket for rainy or windy days",
    price: 49.99,
    imageUrl: "https://example.com/images/windbreaker.jpg",
    category: "Men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 20,
    name: "Hooded Dress",
    description: "Casual hooded dress for women",
    price: 44.99,
    imageUrl: "https://example.com/images/hooded-dress.jpg",
    category: "Women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 21,
    name: "Kids Hoodie Set",
    description: "Warm hoodie and pants set for kids",
    price: 39.99,
    imageUrl: "https://example.com/images/kids-hoodie-set.jpg",
    category: "Kids",
    sizes: ["S", "M", "L"],
  },
  {
    id: 22,
    name: "Polo Shirt",
    description: "Smart casual polo shirt",
    price: 29.99,
    imageUrl: "https://example.com/images/polo-shirt.jpg",
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
  },
];

export default products;
